### ISSUE TITLE
> Can you upload full log to somewhere like https://gist.github.com/?

### ISSUE THREAD

**Issue by Cyanglacier** [filecoin-project/filecoin#2]
> Can you upload full log to somewhere like https://gist.github.com/?

It take too long to uploading(and my explore is crashed...), may caused by the huge file size, it is 84.9MB
Here is the crash log which i uploaded in Google Drive
[https://drive.google.com/file/d/1nTjGxJ9FD6H4OQ4xjY0rfYSXSOK1bwEJ/view?usp=sharing](https://drive.google.com/file/d/1nTjGxJ9FD6H4OQ4xjY0rfYSXSOK1bwEJ/view?usp=sharing)

_Originally posted by @Cyanglacier in https://github.com/filecoin-project/lotus/issues/1613#issuecomment-622926053_

**Comment by arajasek** [comment]
being studied in lotus #1613
